export const ErrorCodes = {
    API_VALIDATION_ERROR: 'API_VALIDATION_ERROR',
    INVALID_JSON_FORMAT: 'INVALID_JSON_FORMAT',
    REQUEST_FORBIDDEN_ERROR: 'REQUEST_FORBIDDEN_ERROR',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};
export const ErrorCodeMap: { [key: string]: number } = {
    API_VALIDATION_ERROR: 400,
    INVALID_JSON_FORMAT: 400,
    REQUEST_FORBIDDEN_ERROR: 403,
    USER_NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500
};
